### ISSUE TITLE
Normal Object Dataset

### ISSUE THREAD

**Issue by zhc1** [PramuPerera/DeepOneClass#3]
Hi, thank you for your fantastic work!  I think you did augmentation on the normal object dataset. I couldn't find details in your paper. What augmentations did you do? Could you please share the Normal Object Dataset you use for training/testing after augmentation so that I can get similar results as presented in your paper. Thank you very much.

**Comment by PramuPerera** [comment]
Normal object dataset is the Pascal VOC 2007 dataset. I used annotations used in the dataset to crop images.
