### ISSUE TITLE
Questions about Reference Network and Secondary Network while training

### ISSUE THREAD

**Issue by Jincheng-Sun** [PramuPerera/DeepOneClass#5]
Hi,
I have read your paper and I think it is a very good way to combine both compactness and descriptiveness, but I got a little confused about the Reference Network and Secondary Network, you mentioned in your paper in section 3.4 that 'weights between two networks are tied together forcing them to be identical.', does that means the weights of the two networks are identical during training ( for both g(·) and hc(·) )?
Thank you for your time and have a good day!

**Comment by PramuPerera** [comment]
Hello,
Yes. Weights for both g and hc will be the same across two branches.
